# Player Discipline

## Research Question

Do defenders and midfielders differ significantly in their average number of yellow cards during the FIFA World Cup 2026?

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [3]:
player_file = r"C:\Users\Sujan\Desktop\Fifa-World-Cup-2026\data\raw\fbref_player_stats_2026_raw.csv"

In [4]:
players = pd.read_csv(player_file, header=1)

In [5]:
players.shape

(1039, 26)

In [6]:
players[['Player', 'Pos', 'Squad', 'MP', 'Min', 'CrdY']].head(10)

               Player Pos            Squad  MP  Min  CrdY
0    Brenden Aaronson  MF           us USA   1   76     0
1      Thelo Aasgaard  MF        no Norway   1   90     0
2    Hamza Abdelkarim  FW         eg Egypt   4   60     0
3  Hossam Abdelmaguid  DF         eg Egypt   2   59     0
4  Mohamed Abdelmonem  DF         eg Egypt   2   14     0
5            Ali Abdi  DF       tn Tunisia   3  269     0
6     Saud Abdulhamid  DF  sa Saudi Arabia   3  269     1
7   Abdulla Abdullaev  DF    uz Uzbekistan   2  180     0
8     Yusuf Abdurisag  FW         qa Qatar   2   98     0
9     Husam Abu Dahab  DF        jo Jordan   2  178     1

In [7]:
players['Pos'].value_counts()

Pos
MF      344
DF      306
FW      159
FWMF     77
GK       62
DFMF     40
MFFW     36
MFDF     12
DFFW      3
Name: count, dtype: int64

In [8]:
players[['Player', 'Pos', 'Squad', 'MP', 'Min', 'CrdY']].isnull().sum()

Player    0
Pos       0
Squad     0
MP        0
Min       0
CrdY      0
dtype: int64

In [9]:
discipline = players[
    ['Player', 'Pos', 'Squad', 'MP', 'Min', 'CrdY']
].copy()

print("Discipline dataset created.")
print("Rows:", len(discipline))

Discipline dataset created.
Rows: 1039

In [10]:
discipline = discipline[
    discipline['Pos'].isin(['DF', 'MF'])
].copy()

print("Eligible players:", len(discipline))
print("\nPosition counts:")
print(discipline['Pos'].value_counts())

Eligible players: 650

Position counts:
Pos
MF    344
DF    306
Name: count, dtype: int64

In [11]:
discipline['Position_Group'] = discipline['Pos'].map({
    'DF': 'Defender',
    'MF': 'Midfielder'
})

In [12]:
discipline[['Player', 'Pos', 'Position_Group', 'CrdY']].head(10)

                   Player Pos Position_Group  CrdY
0        Brenden Aaronson  MF     Midfielder     0
1          Thelo Aasgaard  MF     Midfielder     0
3      Hossam Abdelmaguid  DF       Defender     0
4      Mohamed Abdelmonem  DF       Defender     0
5                Ali Abdi  DF       Defender     0
6         Saud Abdulhamid  DF       Defender     1
7       Abdulla Abdullaev  DF       Defender     0
9         Husam Abu Dahab  DF       Defender     1
10  Mohammad Abu Hasheesh  DF       Defender     0
11      Mohannad Abu Taha  DF       Defender     1